#!/bin/bash
# My first script

git add *
git commit -m "script auto commit"
git push
curl https://web.cs.manchester.ac.uk/dashboard/update?token=2xyEYZufKgYnIDZ7zKfs3LgQR6y3yc1Vg8Hbt%2BKuhfo -o status.json
cat ./status.json
